name: hello-world
on:

  push: {branches: ["master","main"]} 

  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Say Hello
        run: echo "Hello world!"

      -
        name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
          
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20

      # Initializes CodeQL tools for scanning.
      -
        name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      -
        name: Install
        run: npm ci --quiet --ignore-scripts

      -
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      -
        name: Say Goodbye
        run: echo "Goodbye!"

