name: hello-world
on:

  push: {branches: ["master","main"]} 

  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Say Hello
        run: echo "Hello world!"

      -
        name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."

      -
        name: Check out repository
        uses: actions/checkout@v4

      -
        name: Use local hello-world-action
        uses: ./.github/actions/hello-world-action
      -
        name: Say Goodbye
        run: echo "Goodbye!"

