name: hello-world
on:

  push: {branches: ["master","main"]} 

  pull_request: {branches: ["master","main"]}

  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    array-list:
      nodejs-version: [20.x]
    steps:
      -
        name: Say Hello
        run: echo "Hello world!"

      -
        name: Print Variables
        run: |
          echo "My github repository name is ${{ github.repository }}"
          echo "My Node.JS version is ${{ array-list.nodejs-version }}"
          
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Setup Node.js ${{ array-list.nodejs-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: '.github/workflows/node.js/package-lock.json'
          node-version: ${{ array-list.nodejs-version }}

      # Initializes CodeQL tools for scanning.
      -
        name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      -
        name: Install
        run: npm ci --quiet --ignore-scripts

      -
        name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      -
        name: Say Goodbye
        run: echo "Goodbye!"

